export const GETPRODUCTS = "GETPRODUCTS";
export const GETPRODUCTSUCCESS = "GETPRODUCTSUCCESS";
export const GETPRODUCTFAILUER = "GETPRODUCTFAILUER";
export const SETSELECTEDPRODUCTINDEX = "SETINDEX";
export const LOGINSTARTED = "LOGINSTARTED";
export const LOGINSUCCESS = "LOGINSUCCESS";
export const LOGINFAILUER = "LOGINFAILUER";
