export const GETPRODUCTS = "GETPRODUCTS";
export const GETPRODUCTSUCCESS = "GETPRODUCTSUCCESS";
export const GETPRODUCTFAILUER = "GETPRODUCTFAILUER";
export const SETSELECTEDPRODUCTINDEX = "SETINDEX";
